---
# Source: livy/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: livy
  namespace: livy
  labels:
    app.kubernetes.io/name: livy
    app.kubernetes.io/instance: livy
---
# Source: livy/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: livy-spark
  namespace: livy
  labels:
    app.kubernetes.io/name: livy
    helm.sh/chart: livy-2.0.1
    app.kubernetes.io/instance: livy
